# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ryftone/chintan/darpa/vivado/hardware/gnuradio-zcu106-2020.1/xilinx-zcu106-2020.1.srcs/sources_1/bd/project_1/ip/project_1_xbar_5/project_1_xbar_5.xci
# IP: The module: 'project_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ryftone/chintan/darpa/vivado/hardware/gnuradio-zcu106-2020.1/xilinx-zcu106-2020.1.srcs/sources_1/bd/project_1/ip/project_1_xbar_5/project_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_xbar_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /ryftone/chintan/darpa/vivado/hardware/gnuradio-zcu106-2020.1/xilinx-zcu106-2020.1.srcs/sources_1/bd/project_1/ip/project_1_xbar_5/project_1_xbar_5.xci
# IP: The module: 'project_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ryftone/chintan/darpa/vivado/hardware/gnuradio-zcu106-2020.1/xilinx-zcu106-2020.1.srcs/sources_1/bd/project_1/ip/project_1_xbar_5/project_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_xbar_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
