# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/vcu_uc2_pll.xdc

# XDC: imports/xdc/default.xdc

# Block Designs: bd/project_1/project_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1 || ORIG_REF_NAME==project_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_PS_0_0/project_1_PS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_PS_0_0 || ORIG_REF_NAME==project_1_PS_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_interconnect_2_1/project_1_axi_interconnect_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_axi_interconnect_2_1 || ORIG_REF_NAME==project_1_axi_interconnect_2_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_0_0/project_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_0_0 || ORIG_REF_NAME==project_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_xbar_5/project_1_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_xbar_5 || ORIG_REF_NAME==project_1_xbar_5} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_gpio_0_0/project_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_axi_gpio_0_0 || ORIG_REF_NAME==project_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_xlconstant_0_1/project_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_xlconstant_0_1 || ORIG_REF_NAME==project_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_gpio_0_1/project_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_axi_gpio_0_1 || ORIG_REF_NAME==project_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_xlconstant_0_2/project_1_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_xlconstant_0_2 || ORIG_REF_NAME==project_1_xlconstant_0_2} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_dma_0_0/project_1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_axi_dma_0_0 || ORIG_REF_NAME==project_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_fifo_mm_s_0_0/project_1_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==project_1_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_smartconnect_0_0/project_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_smartconnect_0_0 || ORIG_REF_NAME==project_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_xlconcat_0_0/project_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_xlconcat_0_0 || ORIG_REF_NAME==project_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_s00_regslice_0/project_1_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_s00_regslice_0 || ORIG_REF_NAME==project_1_s00_regslice_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_ds_0/project_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_auto_ds_0 || ORIG_REF_NAME==project_1_auto_ds_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_pc_0/project_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_auto_pc_0 || ORIG_REF_NAME==project_1_auto_pc_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_rs_0/project_1_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_auto_rs_0 || ORIG_REF_NAME==project_1_auto_rs_0} -quiet] -quiet

# XDC: bd/project_1/project_1_ooc.xdc
